export * from './page-footer'
export * from './intro'
export * from './page-header'
export * from './perks'
export * from './banner'
export * from './collaboration'
export * from './statistics'
export * from './advantages'
